# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcB <- function(vec_x, knots, M) {
    .Call(`_argofda_calcB`, vec_x, knots, M)
}

calc_Omega <- function(knots, M) {
    .Call(`_argofda_calc_Omega`, knots, M)
}

penalty_matrix <- function(knots) {
    .Call(`_argofda_penalty_matrix`, knots)
}

